create table public.users (
  id serial not null,
  email character varying(100) not null,
  password_hash character varying(255) not null,
  username character varying(50) not null,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_username_key unique (username)
) TABLESPACE pg_default;

create table public.profiles (
  user_id integer not null,
  name character varying(255) null,
  gender character varying(50) null,
  height_in numeric null,
  weight_lb numeric null,
  main_focus character varying(50) null,
  goal_weight_lb numeric null,
  activity_intensity character varying(50) null,
  fitness_level character varying(50) null,
  injuries text null,
  available_equipment text[] null,
  preferred_workout_days integer null default 3,
  date_of_birth date null,
  constraint profiles_pkey primary key (user_id),
  constraint profiles_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.friends (
  user_id_1 integer not null,
  user_id_2 integer not null,
  constraint user_friends_pk primary key (user_id_1, user_id_2),
  constraint fk_user_1 foreign KEY (user_id_1) references users (id) on delete CASCADE,
  constraint fk_user_2 foreign KEY (user_id_2) references users (id) on delete CASCADE,
  constraint check_ids_order check ((user_id_1 < user_id_2))
) TABLESPACE pg_default;

create table public.friend_requests (
  sender_id integer not null,
  receiver_id integer not null,
  status character varying not null default 'pending'::character varying,
  sent_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint friend_requests_pk primary key (sender_id, receiver_id),
  constraint fk_receiver foreign KEY (receiver_id) references users (id) on delete CASCADE,
  constraint fk_sender foreign KEY (sender_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.exercises (
  id integer generated by default as identity not null,
  name character varying not null,
  description text null,
  category character varying null,
  difficulty_level text null,
  mechanic text null,
  equipment text null,
  primary_muscles text[] null,
  secondary_muscles text[] null,
  instructions text[] null,
  category_major text null,
  images text[] null,
  constraint exercises_pkey primary key (id),
  constraint exercises_name_key unique (name)
) TABLESPACE pg_default;

-- PROGRAMS (The high-level container, e.g., "Summer Shred")
create table public.programs (
  id integer generated always as identity not null,
  user_id integer not null,
  name text not null,
  description text null,
  is_active boolean null default false,
  created_at timestamp with time zone null default now(),
  updated_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint programs_pkey primary key (id),
  constraint programs_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

-- WORKOUT_TEMPLATES (The routine blueprint, e.g., "Leg Day")
create table public.workout_templates (
  id integer generated always as identity not null,
  program_id integer not null,
  name text not null,
  day_order integer null default 1,
  notes text null,
  created_at timestamp with time zone null default now(),
  constraint workout_templates_pkey primary key (id),
  constraint workout_templates_program_id_fkey foreign KEY (program_id) references programs (id) on delete CASCADE
) TABLESPACE pg_default;

-- TEMPLATE_EXERCISES (The recipe for the routine)
create table public.template_exercises (
  id integer generated always as identity not null,
  template_id integer not null,
  exercise_id integer not null,
  target_sets integer null default 3,
  target_reps text null,
  target_weight_lb numeric null,
  rest_seconds integer null default 60,
  order_index integer null default 0,
  constraint template_exercises_pkey primary key (id),
  constraint template_exercises_exercise_id_fkey foreign KEY (exercise_id) references exercises (id) on delete CASCADE,
  constraint template_exercises_template_id_fkey foreign KEY (template_id) references workout_templates (id) on delete CASCADE
) TABLESPACE pg_default;

-- WORKOUT_SESSIONS (The specific instance of going to the gym)
create table public.workout_sessions (
  id integer generated always as identity not null,
  user_id integer not null,
  template_id integer null,
  start_time timestamp with time zone null default now(),
  end_time timestamp with time zone null,
  status text null default 'in_progress'::text,
  duration_min numeric null,
  calories_burned integer null,
  total_volume_lb numeric null,
  notes text null,
  constraint workout_sessions_pkey primary key (id),
  constraint workout_sessions_template_id_fkey foreign KEY (template_id) references workout_templates (id) on delete set null,
  constraint workout_sessions_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

-- WORKOUT_SETS (The actual work performed)
create table public.workout_sets (
  id integer generated always as identity not null,
  session_id integer not null,
  exercise_id integer not null,
  set_number integer not null,
  reps_completed integer null,
  weight_lb numeric null,
  rpe integer null,
  is_warmup boolean null default false,
  created_at timestamp with time zone null default now(),
  constraint workout_sets_pkey primary key (id),
  constraint workout_sets_exercise_id_fkey foreign KEY (exercise_id) references exercises (id),
  constraint workout_sets_session_id_fkey foreign KEY (session_id) references workout_sessions (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.challenges (
  id serial not null,
  user_id integer not null,
  challenge_title character varying(255) not null default ''::character varying,
  challenge_type character varying(50) not null default ''::character varying,
  goal numeric not null default 0,
  current_progress numeric not null default 0,
  is_completed boolean not null default false,
  assigned_at timestamp without time zone not null default CURRENT_TIMESTAMP,
  last_updated timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint challenges_pkey primary key (id),
  constraint fk_challenge_user foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.leaderboard (
  user_id integer not null,
  total_points integer null default 0,
  workouts_completed integer null default 0,
  challenges_completed integer null default 0,
  current_streak_days integer null default 0,
  longest_streak_days integer null default 0,
  total_calories_burned integer null default 0,
  rank integer null,
  last_updated timestamp without time zone null default now(),
  constraint leaderboard_pkey primary key (user_id),
  constraint leaderboard_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.ai_conversations (
  id serial not null,
  user_id integer not null,
  message text not null,
  response text not null,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint ai_conversations_pkey primary key (id),
  constraint fk_conversation_user foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_ai_conversations_user_id on public.ai_conversations using btree (user_id) TABLESPACE pg_default;

create table public.ai_workout_plans (
  id serial not null,
  user_id integer not null,
  goal character varying(100) null,
  generated_at timestamp without time zone null default CURRENT_TIMESTAMP,
  workout_data jsonb not null,
  was_completed boolean null default false,
  feedback_rating integer null,
  feedback_notes text null,
  constraint ai_workout_plans_pkey primary key (id),
  constraint fk_ai_plan_user foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_ai_workout_plans_user_id on public.ai_workout_plans using btree (user_id) TABLESPACE pg_default;